[HCICD-464]: Release Notes Automation
lumada-common-services/gh-composite-actions pull request #102
Opened 2023-09-15 12:31 UTC by mayur-hitachivantara

This PR introduces two workflows:
- Release Notes Draft: Auto-generates and keeps release notes up-to-date upon PR merges into master.
- Update Release Documentation: Automatically updates release.md, syncs to Confluence, and sends Slack notifications for seamless collaboration.

These workflows streamline the release process and keep all stakeholders informed.

Credentials required to run these workflows

- Confluence User Email ID
- Confluence API Token
- Github Token 
- Slack Channel Name

2023-09-19 08:35 UTC, cardosov requested changes

2023-09-19 08:35 UTC, cardosov commented on .github/config.yml
Maybe this file should have a more specific name. `config.yaml` seems to generic to just be inside the `.github` folder

2023-09-20 07:07 UTC, mgaikwad2 commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
In addition to user change as mentioned by Vitor ,  please verify the target space where this page is being created ?

2023-09-20 11:16 UTC, mayur-hitachivantara commented on .github/config.yml
Hii @cardosov  
Can we name the` config.yml `as `draft-config.yml `  or any suggestions for names?

2023-09-20 11:26 UTC, mayur-hitachivantara commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
yes, we need a service account for both Confluence and Github.

2023-09-20 11:28 UTC, mayur-hitachivantara commented on docs/release.md
Yes `docs/release.md` needs to exist beforehand

2023-09-21 08:56 UTC, cardosov commented on .github/config.yml
`draft-release-config.yml`

2023-09-26 12:34 UTC, cardosov requested changes

2023-09-26 12:34 UTC, cardosov commented on .github/draft-release-config.yml
I know I've suggested the name to be `draft-release-config` but I've just noticed that this file is to be used by the `release-drafter` action, so, I think the name should be inline with that. `release-drafter-config.yml` seems a better fit.

2023-09-27 10:06 UTC, mayur-hitachivantara commented on .github/draft-release-config.yml
Ok Vitor I will rename the file

2023-09-27 10:33 UTC, cardosov approved these changes

2023-09-27 10:35 UTC, cardosov requested changes

2023-09-27 10:35 UTC, cardosov commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
I've approved but forgot about this service account thing

2023-09-27 10:38 UTC, mayur-hitachivantara commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
Yes, I will Check with Steve for the above service account for Jira and Github.

2023-09-27 10:40 UTC, mayur-hitachivantara commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
@cardosov Also can we add Releases Info Done until now for gh-composite-action in ` ./docs/release.md ` file.

2023-09-27 10:54 UTC, cardosov commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
Sure

2023-09-28 08:33 UTC, cardosov requested changes

2023-09-28 08:33 UTC, cardosov commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
Still not using the service account.

2023-09-28 08:45 UTC, mayur-hitachivantara commented on .github/workflows/update-release-notes.yml
> +  user_for_confluence: mayur.kadam@hitachivantara.com            # user for API token of Confluence
Waiting for steve reply for service accounts

2023-10-06 11:57 UTC, mayur-hitachivantara commented on .github/workflows/update-release-notes.yml
> +          token: ${{ secrets.HNC_JIRA_CONFLUENCE_TOKEN }}
Token Updated

2023-10-06 11:58 UTC, mayur-hitachivantara commented on .github/workflows/release-drafter.yml
> +          GITHUB_TOKEN: ${{ secrets.HV_ADMIN_GITHUB_TOKEN }}
Token Updated

2023-10-06 11:59 UTC, cardosov approved these changes

2023-10-06 12:02 UTC, vganpisetty approved these changes

2023-10-09 10:34 UTC, merged