[CLEANUP] - Blackduck fix mount
lumada-common-services/gh-composite-actions pull request #48
Opened 2023-01-31 19:30 UTC by Sean-Wu-HV

Fix bug according to https://hitachivantara-eng.slack.com/archives/C03LV5245A9/p1675186564721359.
The mount was incorrect, fixed it by specifying the mount in the action: 
options: --entrypoint "/bin/bash" -v ${{ github.workspace }}:/workdir

2023-02-01 15:38 UTC, itsmemarioss requested changes

2023-02-06 16:15 UTC, cardosov approved these changes

2023-02-08 09:47 UTC, vijayaraj-c approved these changes

2023-02-08 10:58 UTC, cardosov requested changes

2023-02-08 17:20 UTC, cardosov approved these changes

2023-02-09 10:55 UTC, itsmemarioss approved these changes
This run tested this new param 👍🏼 
https://github.com/lumada-design/hv-app-shell/pull/68/checks

2023-02-09 10:59 UTC, merged